---
- name: Install required dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - unzip
    - wget
    - netcat
    - lua5.1
    - openssl
    - libpcre3
    - dnsmasq

- name: Clone Kong source code from GitHub
  git:
    repo: https://github.com/Kong/kong.git
    dest: /usr/src/kong
    version: main  # Replace with the desired branch or tag

- name: Build and install Kong
  command: |
    make install
  args:
    chdir: /usr/src/kong
  become: yes

- name: Configure Kong
  copy:
    src: "{{ playbook_dir }}/templates/kong.conf"
    dest: /etc/kong/kong.conf
  notify: Restart Kong

- name: Create Kong systemd service file
  template:
    src: "{{ playbook_dir }}/templates/kong.service.j2"
    dest: /etc/systemd/system/kong.service
  notify: Reload systemd

- name: Start and enable Kong service
  systemd:
    name: kong
    state: started
    enabled: yes

- name: Reload Kong service
  command: systemctl reload kong
  ignore_errors: yes
  become: yes
