---
- name: Install dependencies
  apt:
    name: "{{ kong_dependencies }}"
    state: present

- name: Download Kong source
  get_url:
    url: "{{ kong_source_url }}"
    dest: /tmp/kong-{{ kong_version }}.tar.gz

- name: Extract source
  unarchive:
    src: /tmp/kong-{{ kong_version }}.tar.gz
    dest: /opt
    remote_src: yes

- name: Build Kong
  make:
    chdir: /opt/kong-{{ kong_version }}

- name: Create symlink for Kong executable
  file:
    src: /opt/kong-{{ kong_version }}/bin/kong
    dest: /usr/local/bin/kong
    state: link

- name: Create Kong configuration directory
  file:
    path: /etc/kong
    state: directory
    owner: kong
    group: kong

- name: Create Kong data directory
  file:
    path: /var/lib/kong
    state: directory
    owner: kong
    group: kong

- name: Create Kong logs directory
  file:
    path: /var/log/kong
    state: directory
    owner: kong
    group: kong

- name: Create Kong startup script
  template:
    src: kong.service.j2
    dest: /etc/systemd/system/kong.service
  notify: reload systemd

- name: Create Kong user
  user:
    name: kong

- name: Start Kong service
  service:
    name: kong
    state: started
